name: Unzip Project

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Unzip Project
        run: unzip ExamGuessAI_GitHubAPK.zip -d extracted

      - name: Move Files
        run: |
          cp -r extracted/* .

      - name: Commit Extracted Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Extracted ZIP files"
          git push
