name: Unzip Project

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip ZIP File
        run: |
          unzip -o ExamGuessAI_GitHubAPK.zip -d extracted

      - name: Copy Files
        run: |
          cp -r extracted/* .

      - name: Commit Files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git diff --cached --quiet || git commit -m "Extracted project files"

          git push
